Subindo new feature 24/02/22
valterbfreitasjr/my_first_project pull request #5
Opened 2022-03-01 23:53 UTC by valterbfreitasjr

2022-03-01 23:56 UTC, mgarcia88 commented on src/contact/contact.html
> +    <script src="../js/source.js" type="text/javascript"></script>
@valterbfreitasjr porque esta assim

2022-03-01 23:57 UTC, mgarcia88 requested changes
pode alterar a cor do texto? @valterbfreitasjr

2022-03-01 23:59 UTC, valterbfreitasjr commented
> pode alterar a cor do texto? @valterbfreitasjr

> Pode, fique  a vontade @mgarcia88 .

2022-03-02 00:00 UTC, mgarcia88 approved these changes
LGTM, paranbens @valterbfreitasjr  ficou muito bom

2022-03-02 00:03 UTC, merged